# Generated by Django 4.2.14 on 2024-07-20 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='configurar_parametros',
            fields=[
                ('id_config', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_aves', models.CharField(max_length=50)),
                ('tem_minima', models.CharField(max_length=50)),
                ('tem_maxima', models.CharField(max_length=50)),
                ('hume_minima', models.CharField(max_length=50)),
                ('hume_maxima', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=20)),
                ('confirmar_contraseña', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='registrar_granja',
            fields=[
                ('id_granja', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_granja', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='registrar_galpon',
            fields=[
                ('id_galpon', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=50)),
                ('capacidad', models.CharField(max_length=50)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='registrar_encargado',
            fields=[
                ('id_encargado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.BigIntegerField()),
                ('id_galpon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.registrar_galpon')),
            ],
        ),
        migrations.CreateModel(
            name='mediciones',
            fields=[
                ('id_medicion', models.AutoField(primary_key=True, serialize=False)),
                ('temperatura', models.CharField(max_length=50)),
                ('humedad', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('id_config_parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.configurar_parametros')),
            ],
        ),
        migrations.AddField(
            model_name='configurar_parametros',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.usuario'),
        ),
    ]
