# Generated by Django 5.0.7 on 2024-07-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_alter_configurar_parametros_hume_maxima_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurar_parametros',
            name='hume_minima',
            field=models.CharField(max_length=50),
        ),
    ]
