# Generated by Django 5.0.7 on 2024-07-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_alter_configurar_parametros_hume_minima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurar_parametros',
            name='hume_minima',
            field=models.IntegerField(),
        ),
    ]
