# Generated by Django 5.0.7 on 2024-07-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_alter_configurar_parametros_hume_minima'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediciones',
            name='promedio_temperatura',
            field=models.IntegerField(default=25),
        ),
    ]
