# Generated by Django 5.0.7 on 2024-07-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_mediciones_promedio_temperatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurar_parametros',
            name='promedio_temperatura',
            field=models.IntegerField(default=25),
        ),
    ]
