# Generated by Django 5.0.7 on 2024-07-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_configurar_parametros_promedio_temperatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrar_encargado',
            name='email',
            field=models.CharField(default='activisionactivision7.@gmail.com', max_length=50),
        ),
    ]
