# Generated by Django 5.0.7 on 2024-08-31 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_alter_configurar_parametros_id_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='registrar_usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='registrar_galpon',
            name='capacidad',
            field=models.IntegerField(max_length=50),
        ),
    ]
