# Generated by Django 5.0.7 on 2024-09-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0010_registrar_usuario_alter_registrar_galpon_capacidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrar_galpon',
            name='capacidad',
            field=models.IntegerField(),
        ),
    ]
