# Generated by Django 5.1.1 on 2024-09-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0011_alter_registrar_galpon_capacidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediciones',
            name='promedio_temperatura',
        ),
        migrations.AlterField(
            model_name='mediciones',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mediciones',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
