# Generated by Django 5.1.1 on 2024-09-20 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0012_remove_mediciones_promedio_temperatura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediciones',
            name='id_config_parametro',
        ),
    ]
