# Generated by Django 5.1.1 on 2024-09-25 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='mediciones',
            fields=[
                ('id_medicion', models.AutoField(primary_key=True, serialize=False)),
                ('temperatura', models.CharField(max_length=50)),
                ('humedad', models.CharField(max_length=50)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='registrar_encargado',
            fields=[
                ('id_encargado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.BigIntegerField()),
                ('email', models.CharField(default='activisionactivision7.@gmail.com', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='registrar_usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='configurar_parametros',
            fields=[
                ('id_config', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_aves', models.CharField(max_length=50)),
                ('tem_minima', models.IntegerField()),
                ('tem_maxima', models.IntegerField()),
                ('hume_minima', models.IntegerField()),
                ('hume_maxima', models.IntegerField()),
                ('promedio_temperatura', models.IntegerField(default=25)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('id_encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apirest.registrar_encargado')),
            ],
        ),
        migrations.CreateModel(
            name='registrar_galpon',
            fields=[
                ('id_galpon', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='registrar_encargado',
            name='id_galpon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apirest.registrar_galpon'),
        ),
        migrations.CreateModel(
            name='registrar_granja',
            fields=[
                ('id_granja', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_granja', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
