# Generated by Django 5.1.1 on 2024-09-27 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customUser',
        ),
    ]
